### PR TITLE
Fixes Error: EISDIR: illegal operation on a directory for relative paths

### LINKED ISSUE #47: Error: EISDIR: illegal operation on a directory
I am experiencing the same problem with every version > `1.4` (`1.4.2` works ok).

Just set the `watchFolder` to be relative: 

`./less` 
`../src/less` (in my case)

and the exception is thrown.

Debugging the code of the latest version (`1.10`) I encountered the following code in `lessWatchCompilerUtils.js:184`:

```javascript
fileWatcher: function fileWatcher(f, files, options, filelist, fileimportlist, watchCallback) {
  if (filelist.indexOf(f) !== -1) return;
  filelist[filelist.length] = f;

  if (f.indexOf('.') !== -1) {
    fileimportlist[f] = fileSearch.findLessImportsInFile(f);
  }
  lessWatchCompilerUtilsModule.setupWatcher(f, files, options, watchCallback);
  for (var i in fileimportlist[f]) {
    if (filelist.indexOf(fileimportlist[f][i]) === -1) {
      lessWatchCompilerUtilsModule.setupWatcher(path.normalize(path.dirname(f) + '/' + fileimportlist[f][i]), files, options, watchCallback);
    }
  }
}
```

this function is called (probably the first time) with `f` set to the `watchFolder` and the second `if` (`if (f.indexOf('.') !== -1)`) will resolve to `true` if `f` has `.` inside it (and every relative folder name does) calling `fileSearch.findLessImportsInFile(f)` which will fail by calling `fs.readFileSync(f, 'utf8')` in `filesearch.js:15`.

The condition `if (f.indexOf('.') !== -1)` if pretty fragile one. Why not checking if `f` is a directory?

Changing the condition to `if (f.lastIndexOf('.') > 2)` solves the problem for me, but it's a hack.

Thank you.

### PR DESCRIPTION
**Pull request by mickeyvip**
Fixes #47 

- [ V] Did you add adequate test and make sure they pass by running `npm run test`
- [ X] Did you add update docs in the `README.md` file?

Changes proposed in this pull request:
- replace code that checks for a directory/file with the useage of `fs`

### CODE REVIEW

**Comment by jonycheung** [comment]
Added 2 comments. I'm happy to fix it myself if you don't have time. Let me know how you want to go.

**Comment by mickeyvip** [comment]
@jonycheung , For some reason I don't see the comments.

**Comment by jonycheung** [comment]
Sorry, I forgot the post the comments. I'm merging this into a branch and will PR into the master soon.

**Comment by mickeyvip** [comment]
Cool! Thank so much!

**Comment by mickeyvip** [comment]
When can we expect the next release?

**Pull request merged**
