### PR TITLE
Added 3rd parameter to work with single input file and single bundle …

### PR DESCRIPTION
**Pull request by daniloster**
…file

Please, accept this change and publish to npm in order to allow the developer to work with a main input file and single bundle file.

### CODE REVIEW

**Comment by daniloster** [comment]
@jonycheung Please, could get me some feedback?

**Comment by jonycheung** [comment]
@daniloster I reviewed the request. I assume that your intention is you don't want any extra imported files to be compiled. LESS already supports this. The best way is follow the LESS convention and add a underscore as the prefix of your filename... in your example, it would be "_aux.less". What do you think?

**Comment by daniloster** [comment]
Hi @jonycheung, my intention is compiling one input file with all its dependencies, but generating just one output based on the input name and condensing all the dependencies in it.
But the compilation must be trigged for any file change. For instance, I have a main.less and test.less; main import test; so if I change test, main must be compiled and include the test changes in it. 

The actual behaviour just compiles main if I change the main.less file. Even, having test being imported in main, it won't if I just change test.less.

I hope I have made me clear at this time. Sorry for my english, I have been improving it.

**Comment by jonycheung** [comment]
1.2.2 should have your change. I pushed it to `npm`.

**Comment by jonycheung** [comment]
Thank you for explaining. It makes sense.

Ideally tho' I'd like to track file dependencies. Maybe later. :)

**Comment by daniloster** [comment]
Thank you for accepting! I will update my dependencies. ;)

**Pull request merged**
